### signup
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
   "email": "sample@sr.io",
   "username": "username1",
   "password": "passworD1#",
   "confirm": "passworD1#"
}

### sigin
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
   "email": "sample@sr.io",
   "password": "passworD1#"
}

### all users
GET http://localhost:8080/api/user
Content-Type: application/json

### get user by id
GET http://localhost:8080/api/user/649f24f5d509e5a9addbc3b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OWYyNGY1ZDUwOWU1YTlhZGRiYzNiMSIsImVtYWlsIjoic2FtcGxlQHNyLmlvIiwiaWF0IjoxNjg4MjM3MDYyLCJleHAiOjE2ODgyNDA2NjJ9.QUtA69hWfLUqsYYIdH4gT4W2CcuVixoWz3sMLQB7KHo


### login with google
GET http://localhost:8080/api/user/google/login
Content-Type: application/json

### login with google
GET http://localhost:8080/api/user/google-user
Content-Type: application/json

