### signup
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
   "email": "sample@sr.io",
   "username": "username1",
   "password": "passworD1#",
   "confirm": "passworD1#"
}

### sigin
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
   "email": "sample@sr.io",
   "password": "passworD1#"
}

### all users
GET http://localhost:8080/api/user
Content-Type: application/json

### get user by id
GET http://localhost:8080/api/user/64abe89bfc8a182fb81d747d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YWJlODliZmM4YTE4MmZiODFkNzQ3ZCIsImVtYWlsIjoic2FtcGxlQHNyLmlvIiwidXNlcm5hbWUiOiJzYW1wbGVAc3IuaW8iLCJpYXQiOjE2ODg5ODkxMzMsImV4cCI6MTY4ODk5NjMzM30.9PVfpWRGnNylzrcN5mLwZ5LGsYMSR05aU4l1cvExass


### login with google
GET http://localhost:8080/api/google/login
Content-Type: application/json

### get google user by session
GET http://localhost:8080/api/google/user


### get google user by session
GET http://localhost:8080/api/google/callback