import React from 'react'

import Container from 'react-bootstrap/Container'

const PrivacyPolicy = () => {
  return (
    <Container>
      <h1>Privacy Policy</h1>

      <p>Effective date: July 6, 2023</p>

      <p>
        Xzymous (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates
        the https://www.arnelimperial.com website (hereinafter referred to as
        the &quot;Service&quot;).
      </p>

      <p>
        This page informs you of our policies regarding the collection, use, and
        disclosure of personal data when you use our Service and the choices you
        have associated with that data. The Privacy Policy for Xzymous has been
        created with the help of{' '}
        <a href="https://www.termsfeed.com/privacy-policy-generator/">
          Privacy Policy Generator
        </a>
        .
      </p>

      <p>
        We use your data to provide and improve the Service. By using the
        Service, you agree to the collection and use of information in
        accordance with this policy. Unless otherwise defined in this Privacy
        Policy, the terms used in this Privacy Policy have the same meanings as
        in our Terms and Conditions, accessible from
        https://www.arnelimperial.com
      </p>

      <h2>Definitions</h2>
      <ul>
        <li>
          <p>
            <strong>Service</strong>
          </p>
          <p>
            Service is the https://www.arnelimperial.com website operated by
            Xzymous
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong>
          </p>
          <p>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong>
          </p>
          <p>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>Cookies</strong>
          </p>
          <p>
            Cookies are small files stored on your device (computer or mobile
            device).
          </p>
        </li>
      </ul>

      <h2>Information Collection and Use</h2>
      <p>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </p>
      <p>
        We collect personal information that you provide to us such as name,
        address, contact information, passwords, and social media login data.
      </p>
      <p>
        We collect personal information that you voluntarily provide to us when
        registering at the Services expressing an interest in obtaining
        information about us or our products and services, when participating in
        activities on the Services or otherwise contacting us.
      </p>
      <p>
        The personal information that we collect depends on the context of your
        interactions with us and the Services, the choices you make and the
        products and features you use.
      </p>

      <h3>Types of Data Collected</h3>

      <h4>Personal Data</h4>
      <p>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (&quot;Personal Data&quot;). Personally identifiable
        information may include, but is not limited to:
      </p>

      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Cookies and Usage Data</li>
      </ul>

      <h4>Usage Data</h4>

      <p>
        We may also collect information how the Service is accessed and used
        (&quot;Usage Data&quot;). This Usage Data may include information such
        as your computer&quot;s Internet Protocol address (e.g. IP address),
        browser type, browser version, the pages of our Service that you visit,
        the time and date of your visit, the time spent on those pages, unique
        device identifiers and other diagnostic data.
      </p>

      <h4>Credentials</h4>
      <p>
        We collect passwords, password hints, and similar security information
        used for authentication and account access.{' '}
      </p>

      <h4>Social Media Login Data</h4>
      <p>
        We provide you with the option to register using social media account
        details, like your Facebook, Twitter or other social media account. If
        you choose to register in this way, we will collect the Information
        described in the section called &quot;HANDLING SOCIAL MEDIA LOGINS&quot;
        below.
      </p>
      <h4>Tracking & Cookies Data</h4>
      <p>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information.
      </p>
      <p>
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyse our Service.
      </p>
      <p>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </p>
      <p>Examples of Cookies we use:</p>
      <ul>
        <li>
          <strong>Session Cookies.</strong> We use Session Cookies to operate
          our Service.
        </li>
        <li>
          <strong>Preference Cookies.</strong> We use Preference Cookies to
          remember your preferences and various settings.
        </li>
        <li>
          <strong>Security Cookies.</strong> We use Security Cookies for
          security purposes.
        </li>
      </ul>

      <h2>Use of Data</h2>

      <p>Xzymous uses the collected data for various purposes:</p>
      <ul>
        <li>To facilitate account creation and logon process</li>
        <li>To provide and maintain the Service</li>
        <li>To notify you about changes to our Service</li>
        <li>
          To allow you to participate in interactive features of our Service
          when you choose to do so
        </li>
        <li>To provide customer care and support</li>
        <li>
          To provide analysis or valuable information so that we can improve the
          Service
        </li>
        <li>To monitor the usage of the Service</li>
        <li>To detect, prevent and address technical issues</li>
      </ul>

      <h2>Transfer Of Data</h2>
      <p>
        Your information, including Personal Data, may be transferred to - and
        maintained on - computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ than those from your jurisdiction.
      </p>
      <p>
        If you are located outside Finland and choose to provide information to
        us, please note that we transfer the data, including Personal Data, to
        Finland and process it there.
      </p>
      <p>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </p>
      <p>
        Xzymous will take all steps reasonably necessary to ensure that your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of your data and other personal information.
      </p>

      <h2>Disclosure Of Data</h2>
      <p>
        We only share information with your consent, to comply with laws, to
        provide you with services, to protect your rights, or to fulfill
        business obligations.
      </p>
      <p>We may process or share data based on the following legal basis:</p>
      <ul>
        <li>
          Consent: We may process your data if you have given us specific
          consent to use your personal information in a specific purpose.
        </li>
        <li>
          Legitimate Interests: We may process your data when it is reasonably
          necessary to achieve our legitimate business interests.{' '}
        </li>
        <li>
          Performance of a Contract: Where we have entered into a contract with
          you, we may process your personal information to fulfill the terms of
          our contract.{' '}
        </li>
        <li>
          Legal Obligations: We may disclose your information where we are
          legally required to do so in order to comply with applicable law,
          governmental requests, a judicial proceeding, court order, or legal
          process, such as in response to a court order or a subpoena (including
          in response to public authorities to meet national security or law
          enforcement requirements).
        </li>
        <li>
          Vital Interests: We may disclose your information where we believe it
          is necessary to investigate, prevent, or take action regarding
          potential violations of our policies, suspected fraud, situations
          involving potential threats to the safety of any person and illegal
          activities, or as evidence in litigation in which we are involved.
        </li>
      </ul>
      <h3>Legal Requirements</h3>
      <p>
        Xzymous may disclose your Personal Data in the good faith belief that
        such action is necessary to:
      </p>
      <ul>
        <li>To comply with a legal obligation</li>
        <li>To protect and defend the rights or property of Xzymous</li>
        <li>
          To prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          To protect the personal safety of users of the Service or the public
        </li>
        <li>To protect against legal liability</li>
      </ul>

      <p>
        As an European citizen, under GDPR, you have certain individual rights.
        You can learn more about these guides in the{' '}
        <a href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR">
          GDPR Guide
        </a>
        .
      </p>
      <h2>Retention of Personal Information</h2>
      <p>
        We keep your information for as long as necessary to fulfill the
        purposes outlined in this privacy policy unless otherwise required by
        law.
      </p>
      <p>
        We will only keep your personal information for as long as it is
        necessary for the purposes set out in this privacy policy, unless a
        longer retention period is required or permitted by law (such as tax,
        accounting or other legal requirements). No purpose in this policy will
        require us keeping your personal information for longer than the period
        of time in which users have an account with us.
      </p>
      <p>
        When we have no ongoing legitimate business need to process your
        personal information, we will either delete or anonymize it, or, if this
        is not possible (for example, because your personal information has been
        stored in backup archives), then we will securely store your personal
        information and isolate it from any further processing until deletion is
        possible.
      </p>

      <h2>Security of Data</h2>
      <p>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h2>Service Providers</h2>
      <p>
        We may employ third party companies and individuals to facilitate our
        Service (&quot;Service Providers&quot;), to provide the Service on our
        behalf, to perform Service-related services or to assist us in analyzing
        how our Service is used.
      </p>
      <p>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>

      <h2>Links to Other Sites</h2>
      <p>
        Our Service may contain links to other sites that are not operated by
        us. If you click a third party link, you will be directed to that third
        party&apos;s site. We strongly advise you to review the Privacy Policy
        of every site you visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>

      <h2>Handling Social Logins</h2>
      <p>
        If you choose to register or log in to our services using a social media
        account, we may have access to certain information about you.
      </p>
      <p>
        Our Services offer you the ability to register and login using your
        third party social media account details (like your Facebook or Twitter
        logins). Where you choose to do this, we will receive certain profile
        information about you from your social media provider. The profile
        Information we receive may vary depending on the social media provider
        concerned, but will often include your name, e-mail address, friends
        list, profile picture as well as other information you choose to make
        public.
      </p>
      <p>
        We will use the information we receive only for the purposes that are
        described in this privacy policy or that are otherwise made clear to you
        on the Services. Please note that we do not control, and are not
        responsible for, other uses of your personal information by your third
        party social media provider. We recommend that you review their privacy
        policy to understand how they collect, use and share your personal
        information, and how you can set your privacy preferences on their sites
        and apps.
      </p>

      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 18
        (&apos;Children&apos;).
      </p>
      <p>
        We do not knowingly collect personally identifiable information from
        anyone under the age of 18. If you are a parent or guardian and you are
        aware that your Child has provided us with Personal Data, please contact
        us. If we become aware that we have collected Personal Data from
        children without verification of parental consent, we take steps to
        remove that information from our servers.
      </p>

      <h2>Changes to This Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let you know via email and/or a prominent notice on our Service,
        prior to the change becoming effective and update the &apos;effective
        date&apos; at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact the
        coder.
      </p>
      <ul>
        <li>Email: services@arnelimperial.com</li>
      </ul>
    </Container>
  )
}

export default PrivacyPolicy