name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths-ignore:
      - 'README.md'
jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
        cache-dependency-path: "./server/yarn.lock"
    - run: yarn install
    - run: yarn format && yarn lint
    - run: yarn build:server
    - run: yarn test
      env:
        MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}

  